### ISSUE TITLE
Implement versioning

### ISSUE THREAD

**Issue by MJHeijster** [Madelena/Metrology-for-Hass#12]
Currently HACS will see every commit to the main branch as a new version with the first 7 characters of the last commit as a verion name. [Please use versioning](https://hacs.xyz/docs/publish/start#versions) to push updates to HACS.

Other than that, nice theme!

**Comment by Madelena** [comment]
Thanks for the tip! I didn't know it's pushing every commit to HACS like that... Let me figure it out.

**Comment by Madelena** [comment]
Done! Hope this works. 🤞
