### ISSUE TITLE
Not available via HACS

### ISSUE THREAD

**Issue by Normanras** [Madelena/Metrology-for-Hass#2]
Happy to do the manual install, but wanted to let you know that this isn't showing up in my HACS in either the `integrations` or the `frontend` categories. I searched for both Metrology and Madelena. Here's what I'm running:

Home Assistant Core 2022.5.1
Home Assistant Supervisor 2022.05.0
Home Assistant OS 7.6

All other HACS integrations are working and updated.

**Comment by Madelena** [comment]
Yes, it's currently stuck in the HACS pull request queue right now. 😥

The last theme they added took 24 days to get approved, so it might take a while.

https://github.com/hacs/default/pull/1347

**Comment by Madelena** [comment]
@Normanras It's up on HACS now! 😄
