### ISSUE TITLE
Transparent background on details overview

### ISSUE THREAD

**Issue by kefdk** [Madelena/Metrology-for-Hass#22]
Hi,

On the companion app on iPhone, the detail page for an entity is with a transparent background. This makes it hard to focus on the details, because the lovelace dashboard is still visible.

It would expect a box or a white background.

When checking on a PC it works fine with a box and a no transparency.

See screenshot for the visual issue:

![22-06-04 10-54-47 7009](https://user-images.githubusercontent.com/42749901/171992491-c3119492-b7b6-49c9-bb5d-b95b872c463a.png)

**Comment by Madelena** [comment]
This should be fixed in the latest release 1.2.1, I hope! Please let me know if it still happens after update. Thanks! 😄

**Comment by kefdk** [comment]
I just updated to the mentioned version.

I can confirm this has solved the issue. Thank you for a very quick fix - and a nice theme!
