### ISSUE TITLE
Transparency problem in history

### ISSUE THREAD

**Issue by gaRFio01** [Madelena/Metrology-for-Hass#26]
![DC21D523-8BB7-4858-98CA-FA66B78BE475](https://user-images.githubusercontent.com/105100929/173182130-fc2e4d65-cefd-47f7-bdf2-f1242522c8e3.jpeg)

there is s transparency problem in history ui.
See attached file.

Thanks

**Comment by Madelena** [comment]
I'll take a look at it and see what I can do. Thanks for the report.

**Comment by Madelena** [comment]
This is largely caused by HA erroneously using the `--ha-card-background` color, which I had set to be a transparent color, for dropdowns instead of the opaque dropdown color.

I'll need to investigate to see if I need the card backgrounds to be transparent at all for the next theme overhaul.

**Comment by Madelena** [comment]
Fixed in v1.9

**Comment by Madelena** [comment]
![image](https://user-images.githubusercontent.com/4341881/211190174-d7865545-34ed-4177-b6b3-7fa2cef1bf6c.png)
