### ISSUE TITLE
SegoeUI fonts not showing

### ISSUE THREAD

**Issue by ardevd** [Madelena/Metrology-for-Hass#29]
Installed the theme through HACS and copied this repo's contents in the www folder to my Home assistant www folder. THe stylesheet and fonts don't seem to load for me.

**Comment by Madelena** [comment]
Did you add `/local/style.css` to your Dashboard Resources (http://<your Home Assistant>/config/lovelace/resources)?

**Comment by ardevd** [comment]
The README states `(Optional if you want Segoe UI on non-Windows devices) Copy [style.css](https://github.com/Madelena/Metrology-for-Hass/blob/main/www) and the .ttf font files to /www.` 

So I added the style.css to /www

**Comment by Madelena** [comment]
I realize that my instructions are missing a step.

Besides copying the files, you will also need to go to your HA Settings -> Dashboards -> Resources to add `/local/style.css` as a Stylesheet.

![Settings Screen](https://community-assets.home-assistant.io/optimized/3X/5/3/534fb64a7140d941b96447c7b0c9a062a4b62878_2_690x286.png)
