### ISSUE TITLE
Entities Card Title CSS not working

### ISSUE THREAD

**Issue by marcpizzuto** [Madelena/Metrology-for-Hass#3]
When you add an "Entities" card, if you also add a title to the card, the css renders the title with the grey background colour so the entire card is grey. It should leave the title background white and only make the card's contents background grey.

https://imgur.com/a/rElymIr

**Comment by Madelena** [comment]
The 'title' of cards are meant to be part of a card, so the background should be grey.

The titles with no background are a separate card that I had not released yet.
