### ISSUE TITLE
Theme causes Safe Mode in 2022.8.0b0

### ISSUE THREAD

**Issue by iridris** [Madelena/Metrology-for-Hass#37]
Using the Metrology theme caused HA to go into safe mode when upgrading to 2022.8.0b0.

```
2022-07-27 11:27:16.447 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] while constructing a mapping
in "/config/themes/metro.yaml", line 645, column 7
expected a mapping or list of mappings for merging, but found scalar
in "/config/themes/metro.yaml", line 633, column 11
2022-07-27 11:27:16.449 ERROR (MainThread) [homeassistant.bootstrap] Failed to parse configuration.yaml: while constructing a mapping
in "/config/themes/metro.yaml", line 645, column 7
expected a mapping or list of mappings for merging, but found scalar
in "/config/themes/metro.yaml", line 633, column 11. Activating safe mode
```

This was initially reported as a Core issue but was determined to be a theme issue. Core issue with information about what is triggering this is here: https://github.com/home-assistant/core/issues/75847

**Comment by Madelena** [comment]
There's a code typo as pointed out by @frenck. Thanks for letting me know. I'll push a new fix.

**Comment by Madelena** [comment]
May I ask how you downloaded the theme?

I just downloaded the 1.6.2 prerelease and checked, but the buggy lines that @frenck pointed out had already been removed:
![image](https://user-images.githubusercontent.com/4341881/181523817-2b7e4ecb-ecc3-4451-98f1-39e3cca9cdcc.png)

**Comment by frenck** [comment]
Its on the main branch:

![image](https://user-images.githubusercontent.com/195327/181566346-dc1ace5d-0c4c-49d0-b78a-0589c777ca73.png)

**Comment by Madelena** [comment]
Should be fine now that the code for the bug fixes has merged with the main branch.

**Comment by iridris** [comment]
When this issue occurred, I had the theme manually installed from the main branch. I've now switched over to using HACS to install this. I've installed version 1.6.2 via HACS and restarted Core successfully without issue. Thanks!

**Comment by Madelena** [comment]
@iridris Awesome! I'm glad the bug is fixed. Thanks for testing this. :)
