### ISSUE TITLE
No gap between grid/vertical stack between 1.6.2 and 1.5

### ISSUE THREAD

**Issue by D3v01dZA** [Madelena/Metrology-for-Hass#41]
This could totally be my overuse of grids etc, but it looks like on grid boundaries after the latest update my theme is always displaying incorrectly. Have a look above the weather widget for the most obvious one. If you have a chance please let me know if I did something wrong! Thanks!

1.6.2
![1.6.2](https://user-images.githubusercontent.com/10627822/184258252-05f00919-d5d8-4ce9-8cf7-57e6279e6863.png)

1.5
![1.5](https://user-images.githubusercontent.com/10627822/184258253-e7ff953b-61ac-4d2a-babc-11e2d4a856f7.png)

**Comment by Madelena** [comment]
Thanks for the report. I will take a look at it.

Looks like @fOmey had already fixed it in #40 🤞

**Comment by Madelena** [comment]
@D3v01dZA Your dashboard looks great btw!

**Comment by Madelena** [comment]
It should be fixed in v1.7 now!

**Comment by D3v01dZA** [comment]
Thank you so much!
