### ISSUE TITLE
[Info request] Astrometrics cards?

### ISSUE THREAD

**Issue by sgofferj** [Madelena/Metrology-for-Hass#42]
Hey, love the themes! Would you mind sharing which cards/integrations you used for the astrometics example screenshot? I have been looking for some of those things for a while!

**Comment by Madelena** [comment]
You can find them on my public HASS Config here:

https://github.com/Madelena/hass-config-public/blob/main/ui/views/astrometrics.yaml

https://github.com/Madelena/hass-config-public/blob/main/config/sensors/astrometrics.yaml
