### ISSUE TITLE
Borders inconsistent with 2022.11b0

### ISSUE THREAD

**Issue by iridris** [Madelena/Metrology-for-Hass#46]
On the new beta release of HA, 2022.11b0, borders have been updated. When using the Metrology theme, borders seem to be behaving inconsistently. On the first tab of a dashboard, there's no border as it was on prior versions. However, for any additional tab in the dashboard each card has a border.

First tab:
![image](https://user-images.githubusercontent.com/952387/198150189-13c00edc-d7d9-484e-8eb9-90d3d1ac51ce.png)

Second tab:
![image](https://user-images.githubusercontent.com/952387/198150237-e9989089-bdcf-42d0-b1f8-6d36c8f62510.png)

**Comment by Madelena** [comment]
I'm not on 2022.11b0 yet. Thanks for pointing it out and I'll look into it once I get my hands on it.

**Comment by zanix** [comment]
From the release notes:
> The default dashboard theme has been adjusted to move a little closer to the new Material Design 3 guidelines. Borders around cards are now outlined (instead of having a shadow), and corners are a little more rounded.

**Comment by zanix** [comment]
Adding `ha-card-border-width: 0px` seems to work

```yaml
  # Home Assistant override
  ha-card-box-shadow: "none"
  ha-card-border-width: 0px
```

**Comment by Madelena** [comment]
Thanks @zanix ! Fix is coming up
