### ISSUE TITLE
Creates five "dummy" themes when installed

### ISSUE THREAD

**Issue by chjohans** [Madelena/Metrology-for-Hass#47]
Whenever I install this theme it creates an additional 5 "dummy" themes that appears with the name "_______________" in the themes list. These disappear whenever I delete this theme and appear if I install it again. 

They are even visible in one of the screenshots on the GitHub page here: https://user-images.githubusercontent.com/4341881/177691334-56654b34-b594-4f60-a606-f56ea1591397.png

**Comment by Madelena** [comment]
Yeah, that is unfortunately by design because of how YAML works. The way it is coded allows easy creation of themes and reduces redundant code, with the by-product of these dummy themes.
