### ISSUE TITLE
More visual differentiation of on/off toggles

### ISSUE THREAD

**Issue by Stooovie** [Madelena/Metrology-for-Hass#48]
Hi, I love your theme, the only issue I have is the lack of visual differentiation between ON and OFF states on the switches:

![E01FA319-D0CC-40B4-BDC9-A7F2E678BBD4_1_201_a](https://user-images.githubusercontent.com/10572373/200112225-c4887702-f44b-4a85-9146-ab27924b1b68.jpeg)

How can I make the little ball/circle grey in the OFF state? I tried doing this but it didn't take: 
`switch-unchecked-button-color: "#D0D0D0"`

Thanks!

**Comment by Madelena** [comment]
Hi Stoovie! Thanks for using the theme.

The easiest way to change it would be to change the `rgb-primary-color-darker` value in the Color Variations section of the file.

Also, make sure to run the `Home Assistant Frontend: Reload themes` service (under Developer Tools -> Services) after you make any changes to the theme file.

**Comment by Stooovie** [comment]
<img width="336" alt="Snímek obrazovky 2022-11-05 v 20 39 30" src="https://user-images.githubusercontent.com/10572373/200138004-a6c75acb-1252-4229-aea1-72c51997bec7.png">

Perfect! Thanks!
