### ISSUE TITLE
HACS Store Tiles Overflow

### ISSUE THREAD

**Issue by KyleStilkey** [Madelena/Metrology-for-Hass#49]
It looks like the buttons and texts can go beyond the scaled box under HACS that I've noticed. Doesn't look this way with the default theme.

![image](https://user-images.githubusercontent.com/6766223/200958847-b29bbeac-f258-492c-b757-727b0c072fc6.png)

![image](https://user-images.githubusercontent.com/6766223/200958905-5fd326b7-3c59-46cf-bcd3-65c204104058.png)

**Comment by Madelena** [comment]
![image](https://user-images.githubusercontent.com/4341881/210128782-bbbb2644-bdc8-4b68-85b8-8e6dc6b38785.png)

It should be slightly better now. The Dismiss button would still be cut off if the text is really long, but it should look fine in most cases.
