### ISSUE TITLE
Can't get the look of the device page like the screenshot in Git

### ISSUE THREAD

**Issue by DeepCoreSystem** [Madelena/Metrology-for-Hass#70]
I don't know how to get the device page to look like the screenshot provided in this repo ... V1.9.1 installed

Here is what I get ...

![image](https://github.com/Madelena/Metrology-for-Hass/assets/3703938/7bbcece9-6711-4fb7-9ea5-1a8d93272652)

And this is what I wish for ...

![image](https://github.com/Madelena/Metrology-for-Hass/assets/3703938/4a86864d-a67e-4ba9-865a-c89fa9e27184)

**Comment by Madelena** [comment]
There is a bug with the theme when using HA 2023.10. I will need to fix it. Thanks for letting me know! :)

**Comment by Madelena** [comment]
Ok, I've found the solution. Have you installed the latest version of [card-mod](https://github.com/thomasloven/lovelace-card-mod)? It should fix it.

**Comment by DeepCoreSystem** [comment]
car-mod 3.2.3 is installed, as visible in this screenshot, but the layout doesn't change.
The size of the titles "Automations", "Scenes", "Scripts" and "Logbook" are different in FireFox on Windows vs Debian 12

![image](https://github.com/Madelena/Metrology-for-Hass/assets/3703938/98e2d62f-1112-4086-a653-7273b15cbe68)

**Comment by Madelena** [comment]
The layout isn't controlled by my theme but by Home Assistant Core itself. My screenshot was from an older version, and the HA team had moved things around since.
