### ISSUE TITLE
info on card

### ISSUE THREAD

**Issue by fatshotty** [Madelena/Metrology-for-Hass#73]
Hi, first of all thanks for wonderful theme :)

just a question:
where can I found the source of this dashboard? 
https://user-images.githubusercontent.com/4341881/177698757-b9bffe0e-e9cc-4fb3-8dca-1d07936ec2f7.png
 I mean the "entire solar system" dashboard. It is very beatiful and I would to integrate in my HA
 
 thanks in advance :)

**Comment by Madelena** [comment]
Thank you! 😊

It is my Astrometrics dashboard. You can find it on my public HA config Github repo here: https://github.com/Madelena/hass-config-public/blob/main/ui/views/astrometrics.yaml

**Comment by fatshotty** [comment]
hi, thanks for reply.
I made some work with jsorrery to make it directly usable in a dashboard card in HA without iframe. However it is just an experimental feature; jsorrery uses WebGL and could make browser/app unresponsive

**Comment by Madelena** [comment]
Nice! Please keep me updated 😄
